name: "python package version check"

on:
  workflow_dispatch:
  pull_request:

jobs:
  RunTests:
    name: Run unittests
    container:
      image: ${{vars.ZOETIS_DOCKER_REGISTRY}}/${{vars.PLATFORM_DEVELOPMENT_DOCKER_IMAGE}}:latest
    defaults:
      run:
        shell: bash
    runs-on: vetscan-docker-non-root
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Get changes
      run: git diff --name-only -r HEAD^1 HEAD
  
