name: "python package version check"

on:
  workflow_dispatch:
  pull_request:

jobs:
  AdPythonPackageVersionComment:

    # Only running if it's a PR event
    if: github.head_ref != ''
    name: Commenting python package version
    runs-on: ubuntu-latest
    # runs-on: vetscan-docker-non-root
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Get changes
      run: |
        if [[ -z $(git diff --name-only -r HEAD^1 HEAD | grep setup.py)  ]];
        then
          echo "PYTHON_PACKAGE_VERSION=Did you remember to update the python package version?" >> $GITHUB_ENV;
        fi

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Did you remember

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: Create foo

    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: Update foo
        edit-mode: replace
