name: "python package version check"

on:
  workflow_dispatch:
  pull_request:

jobs:
  RunTests:
    name: Run unittests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Get changes
      run: git diff --name-only -r HEAD^1 HEAD
 
