name: "python package version check"

on:
  workflow_dispatch:
  pull_request:

jobs:
  AdPythonPackageVersionComment:

    # Only running if it's a PR event
    if: github.head_ref != ''
    name: Commenting python package version
    runs-on: ubuntu-latest
    # runs-on: vetscan-docker-non-root
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Check for changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          changes:
            - setup.py

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Python version check

    - name: Create comment bad
      if: steps.filter.outputs.changes == 'false' && steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: **Python Version Check**: ${{inputs.working-directory}} needs version bump (create)

    - name: Create comment good
      if: steps.filter.outputs.changes == 'true' && steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: **Python Version Check**: All good

    - name: Update comment
      if: steps.filter.outputs.changes == 'false' && steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v3
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: **Python Version Check**: ${{inputs.working-directory}} needs version bump (update)
